# Generated by Django 6.0.5 on 2026-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(blank=True, null=True, upload_to='carteles/'),
        ),
    ]
